PocketMonServer/config/routes.rb
Rails.application.routes.draw do
  
  resources :shops
  get 'temp/check'

  resources :pocketmons
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'home#index'
  
  get 'findpocket' => 'pocketmons#findpocket'
  post 'makepocket' => 'pocketmons#makepocket'
  post 'check' => 'temps#check'

end

PocketMonServer/app/models/pocketmon.rb
class Pocketmon < ActiveRecord::Base
    def as_json(options = nil)
        options = {:root => true}
            super(options)
    end
end

PocketMonServer/app/models/shop.rb
class Shop < ActiveRecord::Base
end

PocketMonServer/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

PocketMonServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

PocketMonServer/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
        if current_user.admin == true
            redirect_to rails_admin_path
        else
            render "showerror"
        end     
    end            
  end

  def showerror
  end
end

PocketMonServer/app/controllers/pocketmons_controller.rb
class PocketmonsController < ApplicationController
  before_action :set_pocketmon, only: [:show, :edit, :update, :destroy]

  # GET /pocketmons
  # GET /pocketmons.json
  def index
    @pocketmons = Pocketmon.all
  end

  # GET /pocketmons/1
  # GET /pocketmons/1.json
  def show
  end


  # GET /pocketmons/1/edit
  def edit
  end

  
  def findpocket
    @latitude = params[:lat]
    @longitude = params[:log]
    # 경도 위도를 받아온 다음에 PocketMonList 에서 그거를 탐색
    @pocketmon_list = Pocketmon.where(latitude: (@latitude.to_f-0.5)..(@latitude.to_f+0.5), longitude: (@longitude.to_f-0.5)..(@longitude.to_f+0.5))      
  end

  def makepocket
    @new_pocketmon = Pocketmon.new
    @new_pocketmon[code] = params[:code]
    @new_pocketmon[latitude] = params[:latitude]
    @new_pocketmon[longitude] = params[:longitude]
    @new_pocketmon[level] = params[:level]

    if @new_pocketmon.save
        #성공적으로 저장되었을때
    else
        # 성공적으로 저장하지 못했을때
    end
  end  

  # GET /sellers/new
  def new
    @pocketmon = Pocketmon.new
  end

  # POST /pocketmons
  # POST /pocketmons.json
  def create
    @pocketmon = Pocketmon.new(pocketmon_params)

    respond_to do |format|
      if @pocketmon.save
        format.html { redirect_to @pocketmon, notice: 'Pocketmon was successfully created.' }
        format.json { render :show, status: :created, location: @pocketmon, :root => 'pocketmons' }
      else
        format.html { render :new }
        format.json { render json: @pocketmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pocketmons/1
  # PATCH/PUT /pocketmons/1.json
  def update
    respond_to do |format|
      if @pocketmon.update(pocketmon_params)
        format.html { redirect_to @pocketmon, notice: 'Pocketmon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pocketmon }
      else
        format.html { render :edit }
        format.json { render json: @pocketmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pocketmons/1
  # DELETE /pocketmons/1.json
  def destroy
    @pocketmon.destroy
    respond_to do |format|
      format.html { redirect_to pocketmons_url, notice: 'Pocketmon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pocketmon
      @pocketmon = Pocketmon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pocketmon_params
      params.require(:pocketmon).permit(:code, :latitude, :longitude, :level)
    end
end

PocketMonServer/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:latitude, :longitude, :shoptag, :description)
    end
end

PocketMonServer/app/controllers/temp_controller.rb
class TempController < ApplicationController
  def check
    @temp = Temp.new
    @temp.tempint = [params:tempint]
    @temp.tempfloat = [params:tempfloat]
    @temp.save
  end
end

PocketMonServer/app/helpers/application_helper.rb
module ApplicationHelper
end

PocketMonServer/app/helpers/home_helper.rb
module HomeHelper
end

PocketMonServer/app/helpers/pocketmons_helper.rb
module PocketmonsHelper
end

PocketMonServer/app/helpers/shops_helper.rb
module ShopsHelper
end

PocketMonServer/app/helpers/temp_helper.rb
module TempHelper
end

PocketMonServer/app/views/home/showerror.html.erb
<h1> 해당 회원은 관리자가 아닙니다 </h1>

PocketMonServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PocketMachine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %> 
    <%= link_to "Login", new_user_session_path %>
<% end %>
<br>
<br>
<h1> 관리자 이외에 접근이 불가능한 페이지 입니다. </h1>
<%= yield %>

</body>
</html>

PocketMonServer/app/views/pocketmons/_form.html.erb
<%= form_for(@pocketmon) do |f| %>
  <% if @pocketmon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pocketmon.errors.count, "error") %> prohibited this pocketmon from being saved:</h2>

      <ul>
      <% @pocketmon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PocketMonServer/app/views/pocketmons/edit.html.erb
<h1>Editing Pocketmon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pocketmon %> |
<%= link_to 'Back', pocketmons_path %>

PocketMonServer/app/views/pocketmons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pocketmons</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pocketmons.each do |pocketmon| %>
      <tr>
        <td><%= pocketmon.code %></td>
        <td><%= pocketmon.latitude %></td>
        <td><%= pocketmon.longitude %></td>
        <td><%= pocketmon.level %></td>
        <td><%= link_to 'Show', pocketmon %></td>
        <td><%= link_to 'Edit', edit_pocketmon_path(pocketmon) %></td>
        <td><%= link_to 'Destroy', pocketmon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pocketmon', new_pocketmon_path %>

PocketMonServer/app/views/pocketmons/makepocket.html.erb
<h1> 아아아아아아</h1>

PocketMonServer/app/views/pocketmons/new.html.erb
<h1>New Pocketmon</h1>

<%= render 'form' %>

<%= link_to 'Back', pocketmons_path %>

PocketMonServer/app/views/pocketmons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @pocketmon.code %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @pocketmon.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @pocketmon.longitude %>
</p>

<p>
  <strong>Level:</strong>
  <%= @pocketmon.level %>
</p>

<%= link_to 'Edit', edit_pocketmon_path(@pocketmon) %> |
<%= link_to 'Back', pocketmons_path %>

PocketMonServer/app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :shoptag %><br>
    <%= f.text_field :shoptag %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PocketMonServer/app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

PocketMonServer/app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shops</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Shoptag</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.latitude %></td>
        <td><%= shop.longitude %></td>
        <td><%= shop.shoptag %></td>
        <td><%= shop.description %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

PocketMonServer/app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

PocketMonServer/app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @shop.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @shop.longitude %>
</p>

<p>
  <strong>Shoptag:</strong>
  <%= @shop.shoptag %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>

PocketMonServer/app/views/temp/check.html.erb
<h1>Temp#check</h1>
<p>Find me in app/views/temp/check.html.erb</p>